apiVersion: apps/v1
kind: Deployment
metadata:
  name: plane-email-service-wl
  namespace: plane
spec:
  template:
    spec:
      volumes:
        - name: tls-cert
          secret:
            secretName: plane-mail-tls-secret
            items:
              - key: tls.crt
                path: cert.pem
              - key: tls.key
                path: key.pem
