apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: plane-argus-secrets
  namespace: plane
stringData:
  ARGUS_DATABASE_URL: ""
  ARGUS_CONTENT_DATABASE_URL: ""
  ARGUS_FINGERPRINT_SECRET: ""
  ARGUS_INTERNAL_SECRET: ""
  FEATURE_FLAG_SERVER_AUTH_TOKEN: ""
