apiVersion: v1
kind: Service
metadata:
  name: plane-argus
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: argus
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: argus
  ports:
    - name: argus-8100
      port: 8100
      protocol: TCP
      targetPort: 8100
