apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plane-postgres
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: postgres
spec:
  serviceName: plane-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plane-enterprise
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plane-enterprise
        app.kubernetes.io/component: postgres
    spec:
      serviceAccountName: plane-srv-account
      containers:
        - name: postgres
          image: postgres:15.7-alpine
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: plane-pgdb-secrets
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/plane
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
