apiVersion: apps/v1
kind: Deployment
metadata:
  name: plane-api-wl
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plane-enterprise
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plane-enterprise
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: plane-srv-account
      containers:
        - name: api
          image: artifacts.plane.so/makeplane/backend-commercial:v2.3.3
          imagePullPolicy: Always
          command:
            - ./bin/docker-entrypoint-api-ee.sh
          envFrom:
            - configMapRef:
                name: plane-app-vars
            - secretRef:
                name: plane-app-secrets
            - secretRef:
                name: plane-doc-store-secrets
            - secretRef:
                name: plane-opensearch-secrets
            - secretRef:
                name: plane-silo-secrets
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 1000Mi
              cpu: 500m
