apiVersion: apps/v1
kind: Deployment
metadata:
  name: plane-beat-worker-wl
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: beat-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plane-enterprise
      app.kubernetes.io/component: beat-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plane-enterprise
        app.kubernetes.io/component: beat-worker
    spec:
      serviceAccountName: plane-srv-account
      containers:
        - name: beat-worker
          image: makeplane/backend-commercial:v2.3.4
          imagePullPolicy: Always
          command:
            - ./bin/docker-entrypoint-beat.sh
          envFrom:
            - configMapRef:
                name: plane-app-vars
            - secretRef:
                name: plane-app-secrets
            - secretRef:
                name: plane-doc-store-secrets
            - secretRef:
                name: plane-opensearch-secrets
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 1000Mi
              cpu: 500m
