apiVersion: apps/v1
kind: Deployment
metadata:
  name: plane-web-wl
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plane-enterprise
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plane-enterprise
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: plane-srv-account
      containers:
        - name: web
          image: makeplane/web-commercial:v2.3.3
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: plane-app-vars
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 1000Mi
              cpu: 500m
