apiVersion: apps/v1
kind: Deployment
metadata:
  name: plane-worker-wl
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plane-enterprise
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plane-enterprise
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: plane-srv-account
      containers:
        - name: worker
          image: artifacts.plane.so/makeplane/backend-commercial:v2.3.3
          imagePullPolicy: Always
          command: 
            - ./bin/docker-entrypoint-worker.sh
          envFrom:
            - configMapRef:
                name: plane-app-vars
            - secretRef:
                name: plane-app-secrets
            - secretRef:
                name: plane-doc-store-secrets
            - secretRef:
                name: plane-opensearch-secrets
            - secretRef:
                name: plane-silo-secrets
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 2000Mi
              cpu: 1000m
