apiVersion: v1
kind: Service
metadata:
  name: plane-admin
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: admin
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: admin
