apiVersion: v1
kind: Service
metadata:
  name: plane-api
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: api
