apiVersion: v1
kind: Service
metadata:
  name: plane-iframely
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: iframely
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8061
      protocol: TCP
      targetPort: 8061
  selector:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: iframely
