apiVersion: v1
kind: Service
metadata:
  name: plane-monitor
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: monitor
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: monitor
