apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plane-monitor
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: monitor
spec:
  serviceName: plane-monitor
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plane-enterprise
      app.kubernetes.io/component: monitor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plane-enterprise
        app.kubernetes.io/component: monitor
    spec:
      serviceAccountName: plane-srv-account
      containers:
        - name: monitor
          image: makeplane/monitor-commercial:v2.3.4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: plane-monitor-vars
          volumeMounts:
            - name: monitor-data
              mountPath: /data
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 1000Mi
              cpu: 500m
  volumeClaimTemplates:
    - metadata:
        name: monitor-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
