apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patches/pod-security-context.json
    target:
      kind: Deployment
  - path: patches/container-security-context.json
    target:
      kind: Deployment
