apiVersion: apps/v1
kind: Deployment
metadata:
  name: plane-webhook-consumer-wl
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: webhook-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plane-enterprise
      app.kubernetes.io/component: webhook-consumer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plane-enterprise
        app.kubernetes.io/component: webhook-consumer
    spec:
      serviceAccountName: plane-srv-account
      containers:
        - name: webhook-consumer
          image: makeplane/backend-commercial:v2.3.4
          imagePullPolicy: Always
          stdin: true
          tty: true
          command:
            - ./bin/docker-entrypoint-webhook-consumer.sh
          envFrom:
            - configMapRef:
                name: plane-app-vars
            - configMapRef:
                name: plane-webhook-consumer-vars
            - secretRef:
                name: plane-app-secrets
            - secretRef:
                name: plane-doc-store-secrets
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pgrep -f "python" > /dev/null
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              memory: 500Mi
              cpu: 250m
            limits:
              memory: 1000Mi
              cpu: 500m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: plane-webhook-consumer-hpa
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: webhook-consumer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: plane-webhook-consumer-wl
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
    scaleUp:
      stabilizationWindowSeconds: 120
