apiVersion: v1
kind: Service
metadata:
  name: plane-node-runner
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: node-runner
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: node-runner
  ports:
    - name: node-runner-3000
      port: 3000
      protocol: TCP
      targetPort: 3000
