apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      kind: Secret
      name: overlay-secret-vars
      fieldPath: stringData.DATABASE_URL
    targets:
      - select:
          kind: Secret
          name: plane-app-secrets
        fieldPaths:
          - stringData.DATABASE_URL
      - select:
          kind: Secret
          name: plane-silo-secrets
        fieldPaths:
          - stringData.DATABASE_URL
