apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: plane-flux-secrets
  namespace: plane
stringData:
  # Will be filled by redis component or overlay
  REDIS_URL: ""
  # Will be filled by rabbitmq component or overlay
  AMQP_URL: ""
