apiVersion: batch/v1
kind: Job
metadata:
  name: plane-minio-bucket-create
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: minio-setup
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plane-enterprise
        app.kubernetes.io/component: minio-setup
    spec:
      restartPolicy: OnFailure
      serviceAccountName: plane-srv-account
      containers:
        - name: create-bucket
          image: minio/mc:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              sleep 10
              mc alias set plane http://plane-minio:9000 admin password
              mc mb plane/uploads --ignore-existing
              mc anonymous set download plane/uploads
              echo "Bucket 'uploads' created successfully"
