apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plane-minio
  namespace: plane
  labels:
    app.kubernetes.io/name: plane-enterprise
    app.kubernetes.io/component: minio
spec:
  serviceName: plane-minio
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plane-enterprise
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plane-enterprise
        app.kubernetes.io/component: minio
    spec:
      serviceAccountName: plane-srv-account
      containers:
        - name: minio
          image: minio/minio:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - minio server /export --console-address ":9090"
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9090
              name: console
          env:
            - name: MINIO_ROOT_USER
              value: admin
            - name: MINIO_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: minio-data
              mountPath: /export
  volumeClaimTemplates:
    - metadata:
        name: minio-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 3Gi
