# This ConfigMap holds all the variables for this overlay
# It won't be deployed to the cluster - it's just used as a source for replacements
apiVersion: v1
kind: ConfigMap
metadata:
  name: overlay-vars
  annotations:
    # This annotation tells Kustomize to not deploy this ConfigMap
    config.kubernetes.io/local-config: "true"
data:
  # Application version used across all images and config
  APP_VERSION: "v2.3.3"
  
  # Domain configuration
  APP_DOMAIN: "plane.mycompany.com"
  
  # Web URL (with protocol)
  WEB_URL: "http://plane.mycompany.com"
  
  # CORS allowed origins (comma-separated)
  CORS_ALLOWED_ORIGINS: "http://plane.mycompany.com,https://plane.mycompany.com"
  
  # Ingress class
  INGRESS_CLASS: "nginx"
  
  # AWS ALB SSL Certificate ARN (required when using ALB ingress controller)
  ALB_SSL_CERT_ARN: "arn:aws:acm:us-east-1:1232423423:certificate/f8e65ac6-a0dd-46d2-8809-dea53ec3b765"

  # Other configuration flags
  IS_AIRGAPPED: "0"
